<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="7.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="7.0.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\src\Blazor.WebAssembly.DynamicCulture\Blazor.WebAssembly.DynamicCulture.csproj" />
    <ProjectReference Include="..\..\Shared\Blazor.WebAssembly.Sample.DynamicCulture.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Common\Client\Program.cs" Link="Program.cs" />
    <Compile Include="..\..\Common\Client\Resources\Translations\Translation.Designer.cs" Link="Resources\Translations\Translation.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Translation.resx</DependentUpon>
    </Compile>

    <EmbeddedResource Include="..\..\Common\Client\Resources\Translations\Translation.resx" Link="Resources\Translations\Translation.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Translation.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\Common\Client\Resources\Translations\Translation.ru.resx" Link="Resources\Translations\Translation.ru.resx">
      <DependentUpon>Translation.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\Common\Client\Resources\Translations\Translation.ja.resx" Link="Resources\Translations\Translation.ja.resx">
      <DependentUpon>Translation.resx</DependentUpon>
    </EmbeddedResource>

    <Content Include="..\..\Common\Client\_Imports.razor" Link="_Imports.razor" />
    <Content Include="..\..\Common\Client\App.razor" Link="App.razor" />
    <Content Include="..\..\Common\Client\Components\**\*" Link="Components\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="..\..\Common\Client\Pages\**\*" Link="Pages\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="..\..\Common\Client\Shared\**\*" Link="Shared\%(RecursiveDir)%(Filename)%(Extension)" />
    <None Include="..\..\Common\Client\Properties\launchSettings.json" Link="Properties\launchSettings.json" />
  </ItemGroup>
</Project>
