//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blazor.WebAssembly.Sample.DynamicCulture.Client.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blazor.WebAssembly.Sample.DynamicCulture.Client.Resources.Translations.Translatio" +
                            "n", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balmy.
        /// </summary>
        internal static string Balmy {
            get {
                return ResourceManager.GetString("Balmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bracing.
        /// </summary>
        internal static string Bracing {
            get {
                return ResourceManager.GetString("Bracing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chilly.
        /// </summary>
        internal static string Chilly {
            get {
                return ResourceManager.GetString("Chilly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me.
        /// </summary>
        internal static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter.
        /// </summary>
        internal static string Counter {
            get {
                return ResourceManager.GetString("Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current count.
        /// </summary>
        internal static string CurrentCount {
            get {
                return ResourceManager.GetString("CurrentCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetch data.
        /// </summary>
        internal static string FetchData {
            get {
                return ResourceManager.GetString("FetchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freezing.
        /// </summary>
        internal static string Freezing {
            get {
                return ResourceManager.GetString("Freezing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take our [brief survey]({0}) and tell us what you think..
        /// </summary>
        internal static string SurveyPrompt {
            get {
                return ResourceManager.GetString("SurveyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is Blazor working for you?.
        /// </summary>
        internal static string SurveyTitle {
            get {
                return ResourceManager.GetString("SurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (C).
        /// </summary>
        internal static string TempC {
            get {
                return ResourceManager.GetString("TempC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temp. (F).
        /// </summary>
        internal static string TempF {
            get {
                return ResourceManager.GetString("TempF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather forecast.
        /// </summary>
        internal static string WeatherForecast {
            get {
                return ResourceManager.GetString("WeatherForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This component demonstrates fetching data from the server..
        /// </summary>
        internal static string WeatherForecast_Description {
            get {
                return ResourceManager.GetString("WeatherForecast_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new app..
        /// </summary>
        internal static string WelcomeToYourNewApp {
            get {
                return ResourceManager.GetString("WelcomeToYourNewApp", resourceCulture);
            }
        }
    }
}
