<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Blazor.WebAssembly.Sample.DynamicCulture.Shared.csproj" />
    <ProjectReference Include="..\Client\Blazor.WebAssembly.Sample.DynamicCulture.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\Common\Server\Controllers\**\*.cs" Link="Controllers\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\..\Common\Server\Pages\**\*.cs" Link="Pages\%(RecursiveDir)%(Filename)%(Extension)" />

    <Content Include="..\..\Common\Server\Pages\**\*.cshtml" Link="Pages\%(RecursiveDir)%(Filename)%(Extension)" />
    <Content Include="..\..\Common\Server\appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\Common\Server\appsettings.Development.json" Link="appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" />

    <None Include="..\..\Common\Server\Properties\launchSettings.json" Link="Properties\launchSettings.json" />
  </ItemGroup>


</Project>
